<?php

use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $menus = <<<'JSON'
[
  {
    "menu_id": 1,
    "parent_id": 0,
    "module": "trips",
    "url": "http://13.92.240.159/demo/public/trips",
    "menu_name": "Trips",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 1,
    "position": "sidebar",
    "menu_icons": "mdi mdi-google-maps fa-fw",
    "active": "1",
    "access_data": "{\"1\":\"0\",\"2\":\"0\",\"3\":\"0\",\"4\":\"1\"}",
    "allow_guest": null,
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 27,
    "parent_id": 0,
    "module": "teams",
    "url": "http://13.92.240.159/demo/public/teams",
    "menu_name": "Teams",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 2,
    "position": "sidebar",
    "menu_icons": "mdi mdi-google-maps fa-fw",
    "active": "1",
    "access_data": "{\"1\":\"0\",\"2\":\"0\",\"3\":\"0\",\"4\":\"1\"}",
    "allow_guest": null,
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 28,
    "parent_id": 0,
    "module": "preferences",
    "url": null,
    "menu_name": "Preferences",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 3,
    "position": "sidebar",
    "menu_icons": "mdi mdi-google-maps fa-fw",
    "active": "1",
    "access_data": "{\"1\":\"0\",\"2\":\"0\",\"3\":\"0\",\"4\":\"1\"}",
    "allow_guest": null,
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 32,
    "parent_id": 0,
    "module": null,
    "url": null,
    "menu_name": "Invite Users",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 1,
    "position": "sidebar",
    "menu_icons": "fa fa-handshake-o",
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\"}",
    "allow_guest": null,
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 33,
    "parent_id": 32,
    "module": null,
    "url": "http://13.92.240.159/demo/public/core/users/coordinator",
    "menu_name": "Travel Coordinator",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 0,
    "position": "sidebar",
    "menu_icons": null,
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\"}",
    "allow_guest": null,
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 34,
    "parent_id": 32,
    "module": null,
    "url": "http://13.92.240.159/demo/public/core/users/hotelmanager",
    "menu_name": "Hotel Manager",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 1,
    "position": "sidebar",
    "menu_icons": null,
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\"}",
    "allow_guest": null,
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 35,
    "parent_id": 0,
    "module": null,
    "url": "http://13.92.240.159/demo/public/corporate",
    "menu_name": "Corporate",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 2,
    "position": "sidebar",
    "menu_icons": "fa fa-building",
    "active": "1",
    "access_data": "{\"1\":\"0\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\"}",
    "allow_guest": null,
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 36,
    "parent_id": 0,
    "module": null,
    "url": "#",
    "menu_name": "Hotels",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 3,
    "position": "sidebar",
    "menu_icons": "fa fa-hotel",
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"1\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\"}",
    "allow_guest": null,
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 37,
    "parent_id": 0,
    "module": null,
    "url": "http://13.92.240.159/demo/public/invoices",
    "menu_name": "Invoices",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 4,
    "position": "sidebar",
    "menu_icons": "fa fa-print",
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"1\",\"6\":\"1\"}",
    "allow_guest": null,
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 38,
    "parent_id": 0,
    "module": null,
    "url": "#",
    "menu_name": "Support Ticket",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 6,
    "position": "sidebar",
    "menu_icons": "fa fa-support",
    "active": "1",
    "access_data": "{\"1\":\"0\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\"}",
    "allow_guest": null,
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 39,
    "parent_id": 0,
    "module": null,
    "url": "http://13.92.240.159/demo/public/user/logout",
    "menu_name": "Logout",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 7,
    "position": "sidebar",
    "menu_icons": "fa fa-sign-out",
    "active": "1",
    "access_data": "{\"1\":\"0\",\"2\":\"1\",\"3\":\"1\",\"4\":\"1\",\"5\":\"1\",\"6\":\"1\"}",
    "allow_guest": null,
    "menu_lang": null
  },
  {
    "menu_id": 40,
    "parent_id": 32,
    "module": null,
    "url": "http://13.92.240.159/demo/public/core/users/corporate",
    "menu_name": "Corporate",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 2,
    "position": "sidebar",
    "menu_icons": null,
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\"}",
    "allow_guest": null,
    "menu_lang": null
  },
  {
    "menu_id": 41,
    "parent_id": 0,
    "module": null,
    "url": "http://13.92.240.159/demo/public/core/users",
    "menu_name": "Users",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 0,
    "position": "sidebar",
    "menu_icons": "fa fa-users",
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"1\",\"6\":\"0\"}",
    "allow_guest": null,
    "menu_lang": null
  },
  {
    "menu_id": 42,
    "parent_id": 36,
    "module": null,
    "url": "http://13.92.240.159/demo/public/systemadmin/hotels",
    "menu_name": "View Hotels",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 0,
    "position": "sidebar",
    "menu_icons": null,
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"1\",\"4\":\"0\",\"5\":\"1\",\"6\":\"0\"}",
    "allow_guest": null,
    "menu_lang": null
  },
  {
    "menu_id": 43,
    "parent_id": 36,
    "module": null,
    "url": "http://13.92.240.159/demo/public/systemadmin/hotels/create",
    "menu_name": "Create Hotel",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 1,
    "position": "sidebar",
    "menu_icons": null,
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\"}",
    "allow_guest": null,
    "menu_lang": null
  },
  {
    "menu_id": 44,
    "parent_id": 45,
    "module": "tripstatussettings",
    "url": "http://13.92.240.159/demo/public/tripstatussettings",
    "menu_name": "Status Settings",
    "menu_type": "internal",
    "role_id": null,
    "deep": null,
    "ordering": 0,
    "position": "sidebar",
    "menu_icons": "fa fa-suitcase",
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"1\"}",
    "allow_guest": null,
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 45,
    "parent_id": 0,
    "module": null,
    "url": "#",
    "menu_name": "Trips",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 5,
    "position": "sidebar",
    "menu_icons": "fa fa-suitcase",
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"1\"}",
    "allow_guest": null,
    "menu_lang": null
  },
  {
    "menu_id": 46,
    "parent_id": 45,
    "module": "tripstatuslogs",
    "url": null,
    "menu_name": "Logs",
    "menu_type": "internal",
    "role_id": null,
    "deep": null,
    "ordering": 1,
    "position": "sidebar",
    "menu_icons": null,
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"1\"}",
    "allow_guest": null,
    "menu_lang": null
  },
  {
    "menu_id": 48,
    "parent_id": 0,
    "module": null,
    "url": "http://13.92.240.159/demo/public/corporate/user",
    "menu_name": "Corporate ",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 5,
    "position": "sidebar",
    "menu_icons": "fa fa-users",
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"1\"}",
    "allow_guest": null,
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 49,
    "parent_id": 0,
    "module": null,
    "url": "http://13.92.240.159/demo/public/hotelmanager/trips",
    "menu_name": "Trips",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": null,
    "position": "sidebar",
    "menu_icons": "fa fa-suitcase",
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"5\":\"1\",\"6\":\"1\"}",
    "allow_guest": null,
    "menu_lang": null
  },
  {
    "menu_id": 50,
    "parent_id": 0,
    "module": null,
    "url": "http://13.92.240.159/demo/public/hotelmanager/agreements",
    "menu_name": "Agreements",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 4,
    "position": "sidebar",
    "menu_icons": "fa fa-handshake-o",
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"1\",\"5\":\"1\",\"6\":\"1\"}",
    "allow_guest": null,
    "menu_lang": null
  },
  {
    "menu_id": 51,
    "parent_id": 0,
    "module": "invoices",
    "url": "http://13.92.240.159/demo/public/revenue",
    "menu_name": "Revenue",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": null,
    "position": "sidebar",
    "menu_icons": null,
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"1\",\"6\":\"1\"}",
    "allow_guest": null,
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 52,
    "parent_id": 0,
    "module": null,
    "url": "http://13.92.240.159/demo/public/booking",
    "menu_name": "Booking",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": null,
    "position": "sidebar",
    "menu_icons": null,
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"1\"}",
    "allow_guest": null,
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 53,
    "parent_id": 0,
    "module": null,
    "url": "http://13.92.240.159/demo/public/client",
    "menu_name": "Client",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": null,
    "position": "sidebar",
    "menu_icons": null,
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\"}",
    "allow_guest": "0",
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 54,
    "parent_id": 0,
    "module": "trips",
    "url": "http://13.92.240.159/demo/public/compare",
    "menu_name": "compare",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 1,
    "position": "sidebar",
    "menu_icons": null,
    "active": "1",
    "access_data": "{\"1\":\"0\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"0\"}",
    "allow_guest": "0",
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 55,
    "parent_id": 0,
    "module": null,
    "url": "http://13.92.240.159/demo/public/hotelmanager/room-listing",
    "menu_name": "room-listing",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 5,
    "position": "sidebar",
    "menu_icons": null,
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"1\",\"6\":\"0\"}",
    "allow_guest": "0",
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 56,
    "parent_id": 58,
    "module": null,
    "url": "http://13.92.240.159/demo/public/hotelmanager/blackout",
    "menu_name": "Blackout dates",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 6,
    "position": "sidebar",
    "menu_icons": null,
    "active": "1",
    "access_data": "{\"1\":\"0\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"5\":\"1\",\"6\":\"0\"}",
    "allow_guest": "0",
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 57,
    "parent_id": 58,
    "module": null,
    "url": "http://13.92.240.159/demo/public/hotelmanager/blackoutReport",
    "menu_name": "Blackout Report",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 10,
    "position": "sidebar",
    "menu_icons": null,
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"1\",\"6\":\"1\"}",
    "allow_guest": "0",
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 58,
    "parent_id": 0,
    "module": null,
    "url": "#",
    "menu_name": "Blackout-date",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 6,
    "position": "sidebar",
    "menu_icons": null,
    "active": "1",
    "access_data": "{\"1\":\"1\",\"2\":\"1\",\"3\":\"0\",\"4\":\"0\",\"5\":\"1\",\"6\":\"0\"}",
    "allow_guest": "0",
    "menu_lang": "{\"title\":{\"id\":\"\"}}"
  },
  {
    "menu_id": 59,
    "parent_id": 0,
    "module": null,
    "url": "http://13.92.240.159/demo/public/Reports",
    "menu_name": "Reports",
    "menu_type": "external",
    "role_id": null,
    "deep": null,
    "ordering": 6,
    "position": "sidebar",
    "menu_icons": null,
    "active": "1",
    "access_data": "{\"1\":\"0\",\"2\":\"0\",\"3\":\"0\",\"4\":\"0\",\"5\":\"0\",\"6\":\"1\"}",
    "allow_guest": "0",
    "menu_lang": null
  }
]
JSON;

        $menus = json_decode($menus, true);

        $url = env('APP_URL_MENU', 'APP_URL');
        foreach ($menus as $menuData) {
            $menu = new \App\Models\Sximo\Menu();

            $menu->menu_id     = $menuData['menu_id'];
            $menu->parent_id   = $menuData['parent_id'];
            $menu->module      = $menuData['module'];
            $menu->url         = str_replace(
                'http://13.92.240.159/demo/public/',
                url($url) . '/',
                $menuData['url']
            );
            $menu->menu_name   = $menuData['menu_name'];
            $menu->menu_type   = $menuData['menu_type'];
            $menu->role_id     = $menuData['role_id'];
            $menu->deep        = $menuData['deep'];
            $menu->ordering    = $menuData['ordering'];
            $menu->position    = $menuData['position'];
            $menu->menu_icons  = $menuData['menu_icons'];
            $menu->active      = $menuData['active'];
            $menu->access_data = $menuData['access_data'];
            $menu->allow_guest = $menuData['allow_guest'];
            $menu->menu_lang   = $menuData['menu_lang'];

            $menu->save();
        }

    }
}
