<?php

use Faker\Generator as Faker;

$factory->define(\App\Models\Hotel::class, function (Faker $faker) {
    //-- Hotel names picked from
    // https://en.wikipedia.org/wiki/List_of_hotels_in_the_United_States#Florida
    $hotel_names = [
        'Arcade Hotel',
        'Belleview-Biltmore Hotel',
        'Boca Raton Resort',
        'Carling Hotel',
        'Casa Marina Hotel',
        'Casa Monica Hotel',
        'Chalet Suzanne',
        'Coral Gables Biltmore Hotel',
        'Dixie Walesbilt Hotel',
        'Don CeSar',
        'Fort Harrison Hotel',
        'Henry B. Plant Museum',
        'Hotel George Washington',
        'Hyatt Regency Jacksonville',
        'Kenilworth Lodge',
        'Ormond Hotel',
        'Plaza Hotel',
        'Polk Hotel',
        'Ponce De Leon Boutique Hotel',
        'Ponce de Leon Hotel',
        'Ponte Vedra Inn and Club',
        'Ritz Plaza Hotel',
        'Royal Poinciana Hotel',
        'Streamline Hotel',
        'Vinoy Park Hotel',
        'Well\'sbuilt Hotel',
        'World Golf Village',
        'Cadillac Hotel',
        'Capital at Brickell',
        'Clinton Hotel Miami Beach',
        'The Creek South Beach',
        'Delano Hotel',
        'Doral Hotel',
        'DuPont Plaza Hotel',
        'Eden Roc Renaissance Hotel Miami Beach',
        'EPIC Miami Residences and Hotel',
        'Espirito Santo Plaza',
        'Flamingo Hotel, Miami Beach',
        'Fontainebleau Miami Beach',
        'Four Seasons Hotel Miami',
        'The Grand Doubletree',
        'Icon Brickell',
        'Mandarin Oriental, Miami',
        'Marquis Residences',
        'Met 2 Marriott Marquis',
        'Miccosukee Resort and Gaming',
        'Mondrian Hotel',
        'Ocean Spray Hotel',
        'Ritz Plaza Hotel',
        'Saxony Hotel',
        'The Surfcomber Hotel',
        'W Miami Hotel',
        'Court of Flags Resort',
        'Marriott\'s Grande Vista',
        'Marriott\'s Orlando World Center',
        'Nickelodeon Suites Resort',
        'Parliament House',
        'The Peabody Orlando',
        'Seminole Hotel',
        'Seralago Hotel & Suites Main Gate East',
        'Well\'sbuilt Hotel',
        'Walt Disney World area',
        'Bay Lake Tower',
        'Best Western Lake Buena Vista Resort Hotel',
        'Buena Vista Palace Resort & Spa',
        'Disney\'s All-Star Movies Resort',
        'Disney\'s All-Star Music Resort',
        'Disney\'s All-Star Sports Resort',
        'Disney\'s Animal Kingdom Lodge',
        'Disney\'s Art of Animation Resort',
        'Disney\'s Beach Club Resort',
        'Disney\'s BoardWalk Resort',
        'Disney\'s Caribbean Beach Resort',
        'Disney\'s Contemporary Resort',
        'Disney\'s Coronado Springs Resort',
        'Disney\'s Grand Floridian Resort & Spa',
        'Disney\'s Old Key West Resort',
        'Disney\'s Polynesian Resort',
        'Disney\'s Pop Century Resort',
        'Disney\'s Port Orleans Resort',
        'Disney\'s Wilderness Lodge',
        'Disney\'s Yacht Club Resort',
        'DoubleTree Suites by Hilton Orlando – Lake Buena Vista',
        'Hilton Walt Disney World',
        'Holiday Inn in the Walt Disney World Resort',
        'Royal Plaza Hotel',
        'Shades of Green',
        'Walt Disney World Dolphin',
        'Walt Disney World Swan',
        'Wyndham Lake Buena Vista',
    ];

    return [
        'hotel_code'      => $faker->asciify('********************'),
        'service_type'    => $faker->boolean,
        'name'            => $faker->randomElement($hotel_names),
        'address'         => $faker->address,
        'city'            => $faker->city,
        'zip'             => $faker->postcode,
        'state'           => 'FL',
        'phone'           => $faker->phoneNumber,
        'type'            => '',
        'domain'          => '',
        'logo'            => '',
        'property'        => '',
        'rating'          => '',
        'active'          => 1,
        'IATA_number'     => $faker->asciify('********************'),
        'blackout_start'  => '',
        'blackout_end'    => '',
        'blackout_reason' => '',
        'test'            => '',
    ];
});
