<?php 
return [
'cnf_appname' 			=> 'Sports Travel HQ',
'cnf_appdesc' 			=> 'Booking Hotels  for Sports Team  Made Easy',
'cnf_comname' 			=> 'STravelHQ',
'cnf_email' 			=> 'info@SportsTravelHQ.com',
'cnf_metakey' 			=> 'Hotel Search, Proposals, Contract Singning, Rooming List.',
'cnf_metadesc' 		=> 'Booking Hotels for Sports Team Made Easy',
'cnf_group' 			=> '3',
'cnf_activation' 		=> 'confirmation',
'cnf_multilang' 		=> '1',
'cnf_lang' 			=> 'en',
'cnf_regist' 			=> 'true',
'cnf_front' 			=> 'true',
'cnf_recaptcha' 		=> 'false',
'cnf_theme' 			=> 'sportstravel',
'cnf_backend' 			=> 'minimal',
'cnf_recaptchapublickey' => '6Le2bjQUAAAAABascn2t0WsRjZbmL6EnxFJUU1H_',
'cnf_recaptchaprivatekey' => '6Le2bjQUAAAAAI6ZKqgzoYS21umpeper74sMK38s',
'cnf_mode' 			=> 'production',
'cnf_logo' 			=> 'backend-logo.jpg',
'cnf_allowip' 			=> '',
'cnf_restrictip' 		=> '192.116.134 , 194.111.606.21 ',
'cnf_mail' 			=> 'swift',
'cnf_maps' 			=> 'AIzaSyAayRr-0yZ1ejGGX6l--XDVbHWU85wPj9U',
'cnf_date' 			=> 'Y-m-d',
];
